[package]
name = "shy"
version = "0.1.0"
authors = ["chris west <c@xvxx.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = { version = "3.1.4", features = ["termination"] }
flume = "0.7.1"
termion = "1.5.5"